{{ if .Values.web.certificates.externalSecret.enabled }}

apiVersion: v1
kind: Secret

metadata:
    name: {{ .Values.web.certificates.externalSecret.name }}
type: Opaque

data:
    keystore.p12: |-
        MIINbwIBAzCCDTUGCSqGSIb3DQEHAaCCDSYEgg0iMIINHjCCB9UGCSqGSIb3DQEHAaCCB8YEggfC
        MIIHvjCCA/0GCyqGSIb3DQEMCgEDoIIDxTCCA8EGCiqGSIb3DQEJFgGgggOxBIIDrTCCA6kwggKR
        oAMCAQICBwFyYAUWJ2EwDQYJKoZIhvcNAQEMBQAwTjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDEVE
        REdFL0FCQUN1czEPMA0GA1UECxMGQUJBQ3VzMRcwFQYDVQQDEw5BQkFDdXMgVGVzdCBDQTAeFw0y
        NDA5MDkyMTUyNDJaFw0yNTA5MTAyMTUyNDJaME8xCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxFRERH
        RS9BQkFDdXMxDzANBgNVBAsTBkFCQUN1czEYMBYGA1UEAxMPZGF0YXdhdmUuc2VydmVyMIIBIjAN
        BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyOjZ329Z96TGSjqOReX3lSxF2OWj26dzSXIo0FIq
        lWS56ShT1b4ZxjGs3Q77kHQSzcKviOC2XbJJcOXbMR4vKrruYHn4oyQeaYZFU1a/CSWuTvw2+jWG
        L1gUL8tzOG1y0+ED+HB7WHKv2q1zbdU+xixzP4zyEn40gyWZ+7Y0Pl1L0dsGvRsNo8R3RbivdINz
        NDoCHQyX23VwcWLDQYfbYzidc9QSTCtU0XXjOBxB+AG4uvBj2A7AwmFEXBQ6BmS2kYW+1YDeXnEW
        s5BnWHoMYfZM5UqZxQG/UUacC0R7AkqIzUZlAX+vbz2LssTWfFWOGGK8684doPiVSGeESRqghQID
        AQABo4GKMIGHMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMCcGA1UdJQQgMB4GCCsGAQUF
        BwMBBggrBgEFBQcDAgYIKwYBBQUHAwQwHQYDVR0OBBYEFIH6w/DFZiSlHzXBJnX85uYbsO7EMB8G
        A1UdIwQYMBaAFBXKJga0G8NhAxB/yyV/uyTzO7ukMA0GCSqGSIb3DQEBDAUAA4IBAQAY8Cl+YpVm
        qhq3dd7pHW3Uk6Hg351+JvbgfcNWavRQ0i3DMLj/bzg2dNlJ3WKS211xeRWzBxfWYDuXVMD66TGe
        eIlt0/BNyZWarIu6wNB5U9GDTallB5ZyVlj0LQKGdPXSzDhKgIUXUDhmqzW0sMRonsDtB/tautby
        1gjE4J4vKIg50K8JFIgL43msXmkLXGdvXCEqO8nwjqzSQF9PYNvMVTr3+H4pkFPRqZ5psyn4cUp4
        L81dfFnUlYHMP+oO7o1/zCy9VJiEoLZ2sTdPXqIHAcnnVtmquWyYotCwf2W2QHG1l6ePsboGlyVQ
        t3skTYGLsd+/tsI3EU8hveaSCctUMSUwIwYJKoZIhvcNAQkVMRYEFKKKB+OSIp5iRWkA1Sk29RvW
        4kvuMIIDuQYLKoZIhvcNAQwKAQOgggOoMIIDpAYKKoZIhvcNAQkWAaCCA5QEggOQMIIDjDCCAnSg
        AwIBAgIHAXJgBHlARjANBgkqhkiG9w0BAQwFADBCMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRURE
        R0UvQUJBQ3VzMRwwGgYDVQQDExNBQkFDdXMgVGVzdCBSb290IENBMB4XDTI0MDkwOTIxNDYzNFoX
        DTI1MDkxMDIxNDYzNFowTjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDEVEREdFL0FCQUN1czEPMA0G
        A1UECxMGQUJBQ3VzMRcwFQYDVQQDEw5BQkFDdXMgVGVzdCBDQTCCASIwDQYJKoZIhvcNAQEBBQAD
        ggEPADCCAQoCggEBAI4pihGOPwp1nfOg2rJnk0PeDJzVjnMlOW/saj7PQdarIXFNvkiqdbKQ79rL
        2mtRR/bgw6o1TSiLDK0U2OUzZo9a12m6ed4fX5FtDAwRZb6nXQp66755xE7jbuo86YUmv3f7p1Gz
        m25CVRrJvIK1vQ9nqcx6kgvLA4gP4M+BHFGGLhMDGwfKciE5xnjMa6TNKTAX+jgBA/QaEmbDU6pI
        aZOMqAONPs6hfFlfvB7JBTvhwqmQ+N1zbAEsNsj0msbsrgGWe7q9DyjzoKNw4XhD0v8rgNNX0r1D
        Moz4IYhv7nhXzG5DaFK3amDzySt/ALfHSxbNiKbKDq20tktMvSLrS2UCAwEAAaN7MHkwDwYDVR0T
        AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0OBBYEFBXKJga0G8NhAxB/yyV/uyTzO7uk
        MB8GA1UdIwQYMBaAFGI1YrEXwQ19xLonj+rkSJWF/ePMMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMB
        MA0GCSqGSIb3DQEBDAUAA4IBAQBZQUPkfCuz0eRHScB3M9cc86TOfgmJEHTQxei3++ajckmGmlhd
        qEUSSRMrNXc31NTKPUYsJcs/pQcGl9OORIB2JaiTpFf7yjV3l/sH5AGTppx+kcVahDSEddDh7+xX
        VgQVNMN91jIsc6ONyv9R+JQ9/P5+tq19FJKoyxqJIXx4HpQoqdr/7XxNNtDHwHD5/HFUCTTUv73X
        PJhRBZIyPRP6ijGd8S5wVKX9xV0j1xDNjwC1dgtu4CpffoaYi/CWL2aKhGFhqaVd4e5LdqWn7m/C
        IferrBoVDh7IK1mq62t/xZypz+hNOOuqIzBe+fllI3H+cMgwxUjJleQQD4+k+JPiMIIFQQYJKoZI
        hvcNAQcBoIIFMgSCBS4wggUqMIIFJgYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAED
        MA4ECAuU7PXZ6tAjAgIIAASCBMi/4aom8lQ7r3Aj/eJS0bZDTX2Y6KuAaaBhKmHvhPmon8aTHQvY
        ucc0MRhgaQfMgWfcTHwM1baH4wnMxdjxfiyCYhOH913pyamQTFN+hYS28Otu5IfYHpgo60umpmm6
        wqXJlOTp8L/i6cnFBVR/NBt72TnRIFLRdWFci8Ikum1ZmaClcDydrLUSBfwVh8g7cJtxySPM+CQm
        qZoerQbTSJsHagV/HptURom73yUOT/Wes7EFgbSwd00a27MXDX83b4AwRUCLyzYQp7RCB5ouhiKP
        Vhi1DfXRaqsBe2sH52dhmwf6XD7Ktn7S1Q2cLx5lPluV+vuj830228jfslHI4TgOnsdEjPx61D5z
        7ziERiUPeTL4CDSkwJeuuHVMYxEENYVbRRbUyHhoTDIQN3TEwJGBznt2ZZ7z8Xt68/wTcZhYwshr
        qIhu//m5utRWxDJ4QEvi6xO1GP5o1K/jjGxzCm94u2JKiPLrcyZyHjxaF/7v6HaynqQDMLf3Mwn7
        NESmApWdLbuECbRA2cK1YG33zo+mS/808H4n4O2CFktvKt5daNFe/nDnFPQiisNBTcGX2kHfSxg6
        GiNbiNYlsAvuqhNHJobgd3nxdjnopcTwSWJ+PBVixG+v9G345VQ/zaFIHccHxp/YJCfIj4VJPzFF
        kMiD0jAxR4guxPAwTO/z0Q+rdqx3Sr6KbOrcr3QUTEP5K+V3HLX4SjkTRymM+0xtqjptb8pNe8pn
        MqqlrrInKlaDOkEA6EKFdZ6t2zzuf1wmDDdVGDBSBgU9ie1/N6th0s3fHiWNBCVchlOnTj1IeU4I
        j8W0JkCqHkhMwyGurEkQ4jibWsLf8yEzQjkpmQD7JX94bn0Ym9Xxhy2YnS60v1ohjQmpGclcZ0+o
        ChIUS3b9tdJpzRcBnHG1Y/fy0iiQ8xupN0QPrZDW+FiB6z6Sd8/t6L6O/PNunYOB+oMUZdFfjsKb
        M+qymRvnsunpW5B8VK8gF2LIsZlqbghLdGrP82S/Ywaekb6WDEHd/vm2plzaSCptGg/MhC1GLDAj
        2vnSegxgYxREDcSHSwdRERz5vXH66O14+VKuSczYV2H+xFlmbGmIAVXujRZ3wxkIMAYAWSfZiSSc
        qSjQKdb0WtuTv020BoM52D/R5YL41QQjmX7LH6UDtY264tCNuSXTYDNKyKY2ucmc4DFqxjAU5sm/
        jB55pUYJmgh3UTPs76YWOAvJd2UAP0GixGNcQH61XL7Ikp4VNKKKU/Xzk6scizk+UqZlpCk48mTt
        RIh5kauPnDyD1NiVdADU7BcASNi6wE4CmTBo0oaq5EjBNkgW73m0b8wWPW0U4Vb264ejme+qD+cU
        utxhdg3jVPLcklPcButtMuyPpNtXXfb8rDcculXogJI+7IKwL0d0oxhI8QYYGlm05vuHohCWZxvd
        uNSe8dTAIaV4+ocI7Ksaw1YGgGZbQTiZDBV7pEMID73QaXqjSey3hFKiwh9EBThJImRVc2HGCQO0
        LbZimQ8xCTcmV61AFAhSgOt0oEoasNfMUlUsrdez/rcV/g/q0m7Hp/5UXd5E7cAIKpu1eu2y/eIj
        20da01GzvKdZSZTqEY9Hc9S3Ee+kcalXmrCMWZu6hFToySubDqMx3+gtHXjF7DsxJTAjBgkqhkiG
        9w0BCRUxFgQUoooH45IinmJFaQDVKTb1G9biS+4wMTAhMAkGBSsOAwIaBQAEFNb74TdaOhrU576s
        qkLxbFwJ/iRnBAjYpAnoGMdXUQICCAA=
    truststore.jks: |-
        MIII0gIBAzCCCHwGCSqGSIb3DQEHAaCCCG0EgghpMIIIZTCCCGEGCSqGSIb3DQEHBqCCCFIwgghO
        AgEAMIIIRwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBRGaQn/TU3Q
        TDmFruueNdceaItfhgICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEKPZFpitC424
        eaHr7ft7/juAggfQBLObT1kl40+LWPdq0GsrefikujJWGJlXm3fw6R/1vyr+uJlz6qFQOHMNsuRV
        mx6uPU7SPb6TxtuYgtWCVH0g485J+uLj0GAUPPiDl0kX1bnBeiPQnNDrhp7q3ePHicFx9l1UGoIm
        4fcSrNgtrW7/gHfRBAlX0yDC6Ywo4XyZtBtaReEVuIj5m+f6k0hczp/JXrfEa4JoBg4iSAqLjaWd
        oawWX6IuW4Xo4l+0+iP/LtquoMr6F59fanma557PnsvtvUWk8fDu/vIO9uW50VLKrW/eq08y4LPa
        wVt9FHA9Qx/qrb6FywZpqCSbefARjaS5eDlU8N9HswUvgXBr5r6WiwVgFDP5QK63xhCHJ0ZbkdV7
        spJ8Lkr0bzbuLlpeI+Xq2x8u4+6zVrATdWl03luoYWO3HK7Lj6qjKUF0H9LxADYtoQ2R028pwpSg
        kpDq++TVFEimjyLMuYldbpWokLfWMhH/Y746ZwnMg1g88cNFLFg2DvbH1NmcpkZJx7k+qdm3ySCA
        LKUjz8Txcj5jmnDuS8AoLkNIe33N67xtJT2ObSP61qYX9hB8REZonjAHNcyFv6REEfV8zbU9nTcf
        bydrNTOqMsGhOABLD2AllUC7+N+QFmZ/QYEECuqOS5R131kQNRUIGn+7XlhYSQz9f6FFcLpwLCoI
        i7OcjMkI/Q6FD1u+NkDWn/FMml3hhcnszhapYcPmQfnId1FeikEzqUU/Kwd/xaa942NbpgRFDi1p
        fuIqx7aU8vyW4MNTSldX96EkGduJsEbSQKZ/X8acwQxcsD7tDPw3FIAfS5BwD5x17yp1ILH0zMJx
        2vWUOTPaQwna0OeQqluExtBcAlvht8mZF6qUpywHPrp3mdLjUMYRYx8c4EUHPfQYQ09pMJJT1N3i
        KllyMmCg9+thSdZzn++K9iRZcVPXI79vxVCX4EP4fAZUEqbFiPPUsxfzQ//0vfa/ibhPhMdick+m
        5Ys1aMWBpWx9oRr7Dlvyna5J6v1L50DWHwJWIqAIfoD2FpWKqlGtArdHu8ZVkGB1N1vRgCfwFMrj
        3aQl/1TbH3a1FGpmWOK/NyeyAO0EL0QgLzzi3kC+F+vnYBoY62VKQgAbJqBA6mQe53ICvxCwjAWk
        oNbWwyJ6RQIEQGjqasU1O4AEL2FGs86lDffxjpzhYnkJSmAWuODn0xnOzXsEMXXWpRj/1JuAhcIC
        I5lOjYmF9/8bIDJB47js3WnSFvDYLHH2TOq09yvRMKH+4hNAntUdkCUFRTCxOpdlxxyBMb/Utp3F
        29OXRmJRttL3YR7An4bX8onK1bRmfIa5O+j/gICma4iQECkxKH/IOz55Cyr0IkY09p6dgkU13+b7
        UwIJ6kJBTfoHlOU6oqamQMU+LtJPf29wD9LozVgzATy9cFDgYsw+e6wwC11mRwazNrUHOE6bh5Ab
        /TlQg4wVGYqHhJfCX7Y/JvTiQwTUQLmDDW6PN8+aVEfXnAUhq/Pc9o7qIHYOiSEDMOijOOU7//WM
        9F9uqRErFUV7DIUWVAnlHeDd6boLByzIK46Q7Xfn4QB9dbx0iV5rU5vtXTDoDIjNG6Ul/m77RSC9
        fXv5jE+ALEf2qcrkY2/rhxkNA3pdGIp/kIs+T2zsBSRaur1wEUxEcI1GQzsYT8iXS28iEq2eU56N
        iqZvfzo0yTSr3eTaTJgpzDTIFtNXntRANSWVyaLJyTIpfxv9M4sTalbKX9Qp46jb2u0EugM1Mh1g
        wN7CJMvEdc38uFBG5zjST0HfV9kIlo0H4DI4I2RKMzA/v/J69cKzEiPSAEcDDBXG+XpoDYCVOuk3
        wV5UU1692KpPbFLCrJpO88j/m9uyZh2ADmWppgmZH+LPXE5GGWhvxe6IasWoayQg7gnkYqmEhVWU
        LGxBa2HIWfk/W+wBMHtzMqWswkMJIzM/rAB9N2jE3KEFELJ/SfQpYyEpbYOIdQQVKUJZiMR3WE69
        aJQUpkMQVeSS2WNS2uMWz8NOEi989byEfIMFGPRSjbBhh8gFp46MlFMMoT9rChLe/ffFFxKs+Rss
        WTyWfgyt1Eoecp6/+JKl7Y2/dcoJUMB63ou0J7SNSRdxQLwEdwXg8dINAzkfWg/XEGzF2rEWPHwp
        oRj23o/vFVdnOx4r0t07qhl6fFel+7buMvejz9cBTsxx6WH7+SI3gjVpjqscNgYVMgYbnwwO6LIz
        hqFha9bkgC+jwKcnfq+PTzQpRI1PRAIu24RTj7fZ/rObaSIt0FTQhDwIwrUlFzKwsfYUA8ItMFIf
        sC8Y0UYq1nOO+0Qiuwu3Kyl7rNcHwlPko3q6CasyyGO9YrC9L86vu8duvHqxr22NavH2d1cMDNU/
        ws/dYqwaU1ApKw86PbUXg0XGidnKLYykD36vVLH/MPgT756m+d0syTppKcUs1wmwRQoM4JCyzfKi
        aBCoQ5RpgFCyoqPvkrmuzpLvx7Z2ywdo+5stYyTtdfnPkAHMwu605c71D5u3BEsFSohUgTkYXtgm
        j6AJ80RgsPJrmcYKMa/gnxAAVfmoOrb9Cr82ayi10R9arT+jt+61qGSq/9aSmSiW6cKx00F2uc/L
        asAjbaAO4HvcWD3l3f3cy1NOgXZR+/Tr4zWae7D/iwXUIhIB002xPXrXuZuAhRAG3VDL2TGIsSp0
        eYl6S7hjU7zjA/gUeNwvE7EwTTAxMA0GCWCGSAFlAwQCAQUABCDAOb0qGMefvWbziuJa6UpuCR2O
        IZU1vcrKz4oYquicDAQUj+AI3JX/O0K91EnqBF7Io9pQHecCAicQ

{{ end }}